### ISSUE TITLE
Does this actually do anything?

### ISSUE THREAD

**Issue by iarchiveml** [Aditya20110/Semira1n#2]
Checkra1n 1337's blackbird implementation doesn't support loading custom SEP firmware and since it isn't open source, you'd have to work from scratch. Judging from your previous activity, you are not capable of doing this.

**Comment by edwin170** [comment]
keep going bro, you can do it, implement the Blackbird and i will use it

**Comment by Aditya20110** [comment]
Please dont ask me stupid questions.
